# Generated by Django 5.1.10 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0091_chatmodel_friendly_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchmodelconfig",
            name="embeddings_batch_size",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
